# Generated by Django 6.0.7 on 2026-07-11 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='От 0 до 100 — заработок не может превышать общую выручку кафе.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент с продаж, %'),
        ),
    ]
